name: Review by Change team APP2

on:
  repository_dispatch:
    types: [change-net48-app2-repository-dispatch]

jobs:
  approve:
    environment: 'CHANGE_APP2'
    name: Approve to deploy Production
    runs-on: ubuntu-latest

    steps:
      - run: |

  repository_dispatch:
    name: Repository dispatch
    needs: approve
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Repository dispatch
        run: |
          DISPATCH_BODY=$(jq '.event_type |= "production-net48-app2-repository-dispatch" | .client_payload.git_reference |= "'${{ github.event.client_payload.git_reference }}'"' ./.github/template/env-repository-dispatch.json)
          echo $DISPATCH_BODY
          curl -v --location --request POST 'https://api.github.com/repos/kubeopsskills-enterprise/demo-ais-cicd-pipeline/dispatches' \
            --header 'Authorization: Bearer ${{ secrets.ORG_PAT }}' \
            --header 'accept: application/vnd.github.v3+json' \
            --header 'Content-Type: application/json' \
            --data-raw "$DISPATCH_BODY"
