name: PRODUCTION CD APP2

on:
  repository_dispatch:
    types: [production-net48-app2-repository-dispatch]

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted:net48
    environment: PRODUCTION_APP2
    
    steps:
      - name: AZ Login
        run: az login --identity

      - name: Set Web App Settings
        uses: Azure/appservice-settings@v1
        with:
          app-name: man-net48-prd
          slot-name: 'Production'
          app-settings-json: |
            [
              {
                "name": "SomeSecret",
                "value": "${{ secrets.SOME_SECRET }}",
                "slotSetting": true
              }
            ]

      - name: AZ Logout
        run: az logout

      - name: Download Artifact
        uses: robinraju/release-downloader@v1.3
        with:
          repository: '${{ secrets.ORG_NAME }}/demo-ais-cicd'
          tag: ${{ github.event.client_payload.git_reference }}
          fileName: artifact-net48-app2-${{ github.event.client_payload.git_reference }}.zip
          token: ${{ secrets.ORG_PAT }}

      - name: Unzip Artifact
        run: |
          unzip artifact-net48-app2-${{ github.event.client_payload.git_reference }}.zip
          ls

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: man-net48-prd
          slot-name: 'Production'
          publish-profile: ${{ secrets.APP_SERVICE_PUBLISHPROFILE }}
          package: .

      - name: Cleaning workspace
        run: rm -rf ./*